### PR TITLE
fix typo in docs while config new flightstate object

### PR DESCRIPTION
**Pull request by uzaif313**
typo fix in following section of docs
[https://github.com/uzaif313/node-flightstats/blob/master/docs/API.md#new-flightstatsoptions](Link)

### CODE REVIEW

**Comment by uzaif313** [comment]
can i create PR for support both version `apiKey` or `appKey`?

**Comment by jhermsmeier** [comment]
@uzaif313 sure thing, that'd be great! You can also just update this one, if you like.

**Comment by uzaif313** [comment]
Thanks @jhermsmeier, I will look into it this weekend

**Comment by uzaif313** [comment]
Hi @jhermsmeier , can you please check this commit
https://github.com/uzaif313/node-flightstats/commit/e6c759ec11eaef69d00dd70f4a4290801aaaf012

**Comment by jhermsmeier** [comment]
@uzaif313 looks good to me; although I don't think I'd add `key` – it's a little unspecific

**Pull request closed without merging**
